# Generated by Django 4.2.4 on 2023-09-12 09:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefiEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trading_affected', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('release_date', models.BigIntegerField()),
                ('alert_priority', models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('REMINDER', 'REMINDER')], max_length=30)),
                ('h_spot_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('h_usdm_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('l_spot_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('l_usdm_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('important_dates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('network_tokens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('source', models.CharField(choices=[('OKX', 'Okx'), ('BINANCE', 'Binance'), ('DEFI_LAMA', 'Defi_Lama')], max_length=50, null=True)),
                ('alert_category', models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'hard'), ('CEASE_TRADING', 'cease'), ('TOKEN_DELISTING', 'delist'), ('TOKEN_REMOVAL', 'removal'), ('CONTRACT_UPGRADE', 'contract'), ('SUSPENDED', 'suspended'), ('MIGRATION', 'migration'), ('CONGESTION', 'congestion'), ('SUSPENSION', 'suspension'), ('HACK', 'hack')], max_length=50)),
                ('ms_teams_message', models.JSONField(null=True)),
                ('event_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-release_date'],
                'managed': True,
            },
        ),
    ]
