# Generated by Django 4.2.4 on 2023-08-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_currency', models.CharField(max_length=50)),
                ('base_currency', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alert_priority', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], max_length=50)),
                ('currency_type', models.CharField(choices=[('USDM', 'usdt'), ('SPOT', 'spot')], max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelWirexSpotCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWirexUsdmCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
    ]
