# Generated by Django 4.2.6 on 2023-11-02 20:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_currency', models.CharField(max_length=50)),
                ('base_currency', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alert_priority', models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('REMINDER', 'REMINDER')], max_length=50)),
                ('currency_type', models.CharField(choices=[('SPOT', 'spot'), ('USDM', 'usdm')], max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelDepositCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
                ('name', models.CharField(default='test', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSpotCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStableCoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelUsdmCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEventInterface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trading_affected', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('release_date', models.BigIntegerField()),
                ('alert_priority', models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('REMINDER', 'REMINDER')], max_length=30)),
                ('h_spot_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('h_usdm_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('l_spot_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('l_usdm_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('important_dates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('network_tokens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('source', models.CharField(choices=[('OKX', 'Okx'), ('BINANCE', 'Binance'), ('DEFI_LLAMA', 'Defi'), ('COINMARKETCAP', 'CoinMarketCap'), ('DEFI_LLAMA_STABLECOINS', 'Defi_Stablecoins'), ('BINANCE_ORDERBOOKS', 'Binance/Okx_Spot_Markets')], max_length=200, null=True)),
                ('alert_category', models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'hard'), ('CEASE_TRADING', 'cease'), ('TOKEN_DELISTING', 'delist'), ('TOKEN_REMOVAL', 'removal'), ('CONTRACT_UPGRADE', 'contract'), ('SUSPENDED', 'suspended'), ('MIGRATION', 'migration'), ('CONGESTION', 'congestion'), ('SUSPENSION', 'suspension'), ('HACK', 'hack'), ('DEPEG', 'depeg'), ('BRIDGE_HACK', 'bridge hack'), ('TOKEN_PRICE_VOLATILITY', 'token_price_volatility'), ('TOKEN_LIQUIDITY_EVENT', 'low_liquidity_event')], max_length=200)),
                ('ms_teams_message', models.JSONField(null=True)),
                ('event_completed', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
