# Generated by Django 4.2.6 on 2023-10-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleventinterface',
            name='alert_category',
            field=models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'hard'), ('CEASE_TRADING', 'cease'), ('TOKEN_DELISTING', 'delist'), ('TOKEN_REMOVAL', 'removal'), ('CONTRACT_UPGRADE', 'contract'), ('SUSPENDED', 'suspended'), ('MIGRATION', 'migration'), ('CONGESTION', 'congestion'), ('SUSPENSION', 'suspension'), ('HACK', 'hack'), ('DEPEG', 'depeg'), ('BRIDGE_HACK', 'bridge hack'), ('TOKEN_PRICE_VOLATILITY', 'token_price_volatility')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeleventinterface',
            name='source',
            field=models.CharField(choices=[('OKX', 'Okx'), ('BINANCE', 'Binance'), ('DEFI_LLAMA', 'Defi'), ('DEFI_LLAMA_STABLECOINS', 'Defi_Stablecoins'), ('BINANCE_ORDERBOOKS', 'Binance/Okx_Spot_Markets')], max_length=50, null=True),
        ),
    ]
