# Generated by Django 4.2.4 on 2023-09-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWirexStableCoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
    ]
