# Generated by Django 4.2.6 on 2023-10-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ews_app', '0004_alter_modeleventinterface_h_spot_tickers_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE MATERIALIZED VIEW token_risk_view AS
            SELECT
                split_part(unnest(h_spot_tickers || h_usdm_tickers || network_tokens), '/', 1) AS high_risk_assets
            FROM
                public.ews_app_modeleventinterface
            WHERE
                event_completed = False
            GROUP BY
                high_risk_assets;
        """, """
            DROP MATERIALIZED VIEW IF EXISTS token_risk_view;
        """),  # Reverse SQL for the materialized view

        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION refresh_token_risk_view()
            RETURNS TRIGGER AS $$
            BEGIN
                REFRESH MATERIALIZED VIEW token_risk_view;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """, """
            DROP FUNCTION IF EXISTS refresh_token_risk_view();
        """),  # Reverse SQL for the function

        migrations.RunSQL("""
            CREATE TRIGGER trg_refresh_token_risk_view
            AFTER INSERT OR UPDATE OR DELETE ON public.ews_app_modeleventinterface
            FOR EACH STATEMENT
            EXECUTE FUNCTION refresh_token_risk_view();
        """, """
            DROP TRIGGER IF EXISTS trg_refresh_token_risk_view ON public.ews_app_modeleventinterface;
        """)
    ]