# Generated by Django 4.2.6 on 2023-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews_app', '0005_create_materialized_token_risk_view_and_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWirexDepositCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
    ]
