# Generated by Django 4.2.6 on 2023-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews_app', '0006_modelwirexdepositcurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwirexdepositcurrency',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
