# Generated by Django 4.2.4 on 2023-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBinanceArticle',
            fields=[
                ('url', models.URLField(null=True)),
                ('html', models.CharField(max_length=25000, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alert_priority', models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('REMINDER', 'REMINDER')], max_length=50, null=True)),
                ('alert_category', models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'hard'), ('CEASE_TRADING', 'cease'), ('TOKEN_DELISTING', 'delist'), ('TOKEN_REMOVAL', 'removal'), ('CONTRACT_UPGRADE', 'contract'), ('SUSPENDED', 'suspended'), ('MIGRATION', 'migration'), ('CONGESTION', 'congestion'), ('SUSPENSION', 'suspension'), ('HACK', 'hack'), ('DEPEG', 'depeg'), ('BRIDGE_HACK', 'bridge hack')], max_length=50, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelBinanceArticleRaw',
            fields=[
                ('release_date', models.BigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=300, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
