# Generated by Django 4.2.4 on 2023-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_ews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbinanceevent',
            name='event_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='alert_priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('REMINDER', 'REMINDER')], max_length=30),
        ),
    ]
