# Generated by Django 4.2.4 on 2023-09-07 09:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_ews_app', '0003_create_live_news_matirealised_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbinanceevent',
            name='source',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('OKX', 'Okx')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='h_spot_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='h_usdm_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='important_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='l_spot_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='l_usdm_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='network_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
