# Generated by Django 4.2.4 on 2023-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_ews_app', '0004_modelbinanceevent_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='alert_category',
            field=models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'hard'), ('CEASE_TRADING', 'cease'), ('TOKEN_DELISTING', 'delist'), ('TOKEN_REMOVAL', 'removal'), ('CONTRACT_UPGRADE', 'contract'), ('SUSPENDED', 'suspended'), ('MIGRATION', 'migration'), ('CONGESTION', 'congestion'), ('SUSPENSION', 'suspension'), ('HACK', 'hack')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='source',
            field=models.CharField(choices=[('OKX', 'Okx'), ('BINANCE', 'Binance'), ('DEFI_LAMA', 'Defi_Lama')], max_length=50, null=True),
        ),
    ]
