# Generated by Django 4.2.4 on 2023-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_ews_app', '0007_alter_modelbinanceevent_h_spot_tickers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbinanceevent',
            name='alert_category',
            field=models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'hard'), ('CEASE_TRADING', 'cease'), ('TOKEN_DELISTING', 'delist'), ('TOKEN_REMOVAL', 'removal'), ('CONTRACT_UPGRADE', 'contract'), ('SUSPENDED', 'suspended'), ('MIGRATION', 'migration'), ('CONGESTION', 'congestion'), ('SUSPENSION', 'suspension'), ('HACK', 'hack'), ('DEPEG', 'depeg')], max_length=50),
        ),
    ]
