# Generated by Django 4.2.6 on 2023-10-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ews_app', '0002_alter_modeleventinterface_alert_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTokenVolatilityEvent',
            fields=[
                ('modeleventinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ews_app.modeleventinterface')),
            ],
            options={
                'ordering': ['-release_date'],
                'managed': True,
            },
            bases=('ews_app.modeleventinterface',),
        ),
    ]
