# Generated by Django 4.2.4 on 2023-09-14 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi_llama_ews_app', '0003_modeldefistablecoinevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefiLlamaBridgeHack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacked_amount_m', models.FloatField(null=True)),
                ('release_date', models.BigIntegerField(null=True)),
                ('trading_affected', models.BooleanField(default=False)),
                ('url', models.URLField(null=True)),
                ('protocol', models.CharField(max_length=30, null=True)),
                ('exploit', models.CharField(max_length=30, null=True)),
                ('blockchain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('alert_priority', models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('REMINDER', 'REMINDER')], max_length=50, null=True)),
                ('alert_category', models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'Hard'), ('CEASE_TRADING', 'Cease'), ('TOKEN_DELISTING', 'Delist'), ('TOKEN_REMOVAL', 'Removal'), ('CONTRACT_UPGRADE', 'Contract'), ('SUSPENDED', 'Suspended'), ('MIGRATION', 'Migration'), ('CONGESTION', 'Congestion'), ('SUSPENSION', 'Suspension'), ('HACK', 'Hack'), ('DEPEG', 'Depeg'), ('BRIDGE_HACK', 'Bridge Hack')], max_length=50, null=True)),
                ('network_tokens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='modeldefihackevent',
            name='alert_category',
            field=models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'Hard'), ('CEASE_TRADING', 'Cease'), ('TOKEN_DELISTING', 'Delist'), ('TOKEN_REMOVAL', 'Removal'), ('CONTRACT_UPGRADE', 'Contract'), ('SUSPENDED', 'Suspended'), ('MIGRATION', 'Migration'), ('CONGESTION', 'Congestion'), ('SUSPENSION', 'Suspension'), ('HACK', 'Hack'), ('DEPEG', 'Depeg'), ('BRIDGE_HACK', 'Bridge Hack')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeldefistablecoinevent',
            name='alert_category',
            field=models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'Hard'), ('CEASE_TRADING', 'Cease'), ('TOKEN_DELISTING', 'Delist'), ('TOKEN_REMOVAL', 'Removal'), ('CONTRACT_UPGRADE', 'Contract'), ('SUSPENDED', 'Suspended'), ('MIGRATION', 'Migration'), ('CONGESTION', 'Congestion'), ('SUSPENSION', 'Suspension'), ('HACK', 'Hack'), ('DEPEG', 'Depeg'), ('BRIDGE_HACK', 'Bridge Hack')], max_length=50),
        ),
    ]
