from django.test import TestCase

# Create your tests here.
from binance_ews_app.test.test_binance_ews_converters_test_case import TestBinanceConvertersTestCase
from binance_ews_app.test.test_binance_gala_hard_fork_test_case import  TestBinanceGalaHardForkTestCase
from binance_ews_app.test.test_binance_ews_app_all_services_test_case import TestBinanceEwsAppAllServicesTestCase