# Generated by Django 4.2.4 on 2023-09-12 11:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okx_ews_app', '0002_alter_modelokxevent_alert_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelokxevent',
            name='h_spot_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='modelokxevent',
            name='h_usdm_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='modelokxevent',
            name='important_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='modelokxevent',
            name='l_spot_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='modelokxevent',
            name='l_usdm_tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='modelokxevent',
            name='network_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='modelokxevent',
            name='source',
            field=models.CharField(choices=[('OKX', 'Okx'), ('BINANCE', 'Binance'), ('DEFI_LLAMA', 'Defi')], max_length=50, null=True),
        ),
    ]
