# Generated by Django 4.2.4 on 2023-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okx_ews_app', '0005_alter_modelokxevent_alert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelokxevent',
            name='alert_category',
            field=models.CharField(choices=[('SWAP', 'swap'), ('NETWORK', 'network'), ('UPGRADE', 'upgrade'), ('PROTOCOL', 'protocol'), ('HARD_FORK', 'Hard'), ('CEASE_TRADING', 'Cease'), ('TOKEN_DELISTING', 'Delist'), ('TOKEN_REMOVAL', 'Removal'), ('CONTRACT_UPGRADE', 'Contract'), ('SUSPENDED', 'Suspended'), ('MIGRATION', 'Migration'), ('CONGESTION', 'Congestion'), ('SUSPENSION', 'Suspension'), ('HACK', 'Hack'), ('DEPEG', 'Depeg'), ('BRIDGE_HACK', 'Bridge Hack')], max_length=50),
        ),
    ]
