from ews_app.enum.enum_no_value_interface import NoValue


class EnumBlockchain(NoValue):

    ETHEREUM    = 'ETH'
    TRON        = 'TRX'   
    BSC         = 'BNB'     
    ARBITRUM    = 'ARB'
    POLYGON     = 'MATIC'
    AVALANCHE   = 'AVAX'
    OPTIMISM    = 'OP'
    SOLANA      = 'SOL'
    MIXIN       = 'XIN'
    CRONOS      = 'CRO'
    KAVA        = 'KAVA'
    GNOSIS      = 'GNO'
    FUSION      = 'FSN'
    KLAYTN      = 'KLAY'
    BITCOIN     = 'BTC'
    CARDANO     = 'ADA'
    ACALA       = 'ACA'
    ALGORAND    = 'ALGO'
    OKEXCHAIN   = 'OKT'
    WEMIX       = 'WEMIX'
    CELO        = 'CELO'
    OSMOSIS     = 'OSMO'
    RSK         = 'RBTC'
    EOS         = 'EOS'
    NEAR        = 'NEAR'
    FANTOM      = 'FTM'
    THORCHAIN   = 'RUNE'
    TEZOS       = 'XTZ'
    HEDERA      = 'HBAR'
    HECO        = 'HT'
    APTOS       = 'APT'
    ASTAR       = 'ASTR'
    WAVES       = 'WAVES'
    NEO         = 'NEO'
    CANTO       = 'CANTO'
    ELROND      = 'EGLD'
    MOONBEAM    = 'GLMR'
    CONFLUX     = 'CFX'
    METIS       = 'METIS'
    STELLAR     = 'XLM'
    SECRET      = 'SCRT'
    ICON        = 'ICX'
    STACKS      = 'STX'
    ONTOLOGYEVM = 'ONG'
    ONTOLOGY    = 'ONT'
    IOTEX       = 'IOTX'
    TELOS       = 'TLOS'