from ews_app.enum.enum_no_value_interface import NoValue


class EnumBlockchain(NoValue):

    ETHEREUM    = 'Ethereum'
    TRON        = 'Tron'
    BSC         = 'BSC'
    ARBITRUM    = 'Arbitrum'
    POLYGON     = 'Polygon'
    AVALANCHE   = 'Avalanche'
    OPTIMISM    = 'Optimism'
    SOLANA      = 'Solana'
    MIXIN       = 'Mixin'  
    CRONOS      = 'Cronos' 
    KAVA        = 'Kava'
    BASE        = 'Base'
    GNOSIS      = 'GNOSIS'
    KLAYTN      = 'Klaytn'
    FUSION      = 'Fusion'
    BITCOIN     = 'Bitcoin'
    CARDANO     = 'Cardano'
    ACALA       = 'Acala'
    ALGORAND    = 'Algorand'
    zkSync      = 'zkSync'  
    OKEXCHAIN   = 'OKExChain'
    WEMIX       = 'WEMIX' 
    OSMOSIS     = 'Osmosis'
    CELO        = 'Celo'
    RSK         = 'RSK' 
    EOS         = 'EOS'
    FANTOM      = 'Fantom'
    NEAR        = 'Near'  
    THORCHAIN   = 'Thorchain'
    TEZOS       = 'Tezos'
    HEDERA      = 'Hedera'
    APTOS       = 'Aptos'  
    HECO        = 'Heco'  
    ASTAR       = 'Astar'
    WAVES       = 'Waves'
    NEO         = 'NEO' 
    ELROND      = 'Elrond'  
    CANTO       = 'Canto'
    MOONBEAM    = 'Moonbeam'
    CONFLUX     = 'Conflux'
    METIS       = 'Metis'
    POLYGON     = 'Polygon'  
    ZKEVM       = 'zkEVM'  
    STELLAR     = 'Stellar' 
    STACKS      = 'Stacks'
    ICON        = 'Icon'
    SECRET      = 'Secret'  
    ONTOLOGYEVM = 'OntologyEVM'  
    ONTOLOGY    = 'Ontology'
    IOTEX       = 'IoTeX'
    TELOS       = 'Telos'