from django.db import models

# Create your models here.
from ews_app.model.model_ticker import ModelTicker
from ews_app.model.model_wirex_stablecoin import ModelWirexStableCoin
from ews_app.model.model_wirex_spot_currency import ModelWirexSpotCurrency
from ews_app.model.model_wirex_usdm_currency import ModelWirexUsdmCurrency
from ews_app.model_interfaces.model_event_interface import ModelEventInterface
from ews_app.model.model_wirex_deposit_currency import ModelWirexDepositCurrency